#!/bin/sh
#Submit using flux batch <filename>

#flux: --job-name=Fault_639_n2
#flux: --output='Fault_639_n2.{{id}}.out'
#flux: --error='Fault_639_n2.{{id}}.err'
#flux: -N 2
#flux: -l # Add task rank prefixes to each line of output.
#flux: --setattr=thp=always # Enable Transparent Huge Pages (THP)
#flux: -t 30
#flux: -x
#flux: -q pdebug

export MPICH_GPU_SUPPORT_ENABLED=1
export HSA_XNACK=1

cd ${HOME}/CG/src
folder=/usr/workspace/bienz1/benchmark_mats/SPD
mat=${folder}/Fault_639.pm
flux run -N2 -n8 -g1 ./cg $mat
  
